Table user_group {
  id_relation integer [pk, increment]
  user_id varchar
  group_id integer 
  created_at timestamp
  role varchar 
  status status
  indexes {
    (user_id, group_id) [unique]
  }
}

Table friends {
  friend1 varchar unique
  friend2 varchar
  request friend_request
  checks {
    `friend1 < friend2` [name: 'evitar duplicados']
  }
}

Table groups {
  id integer [pk, increment]
  displayname varchar
  description texto
  created_at timestamp
}

Table track {
  title varchar
  body text [note: 'Content of the post']
  group integer [not null]
  status varchar
  created_at timestamp
  indexes {
    (group, title) [pk]
  }
}

Table log {
  id integer [pk, increment]
  user_id varchar
  track_group integer
  track_title varchar
  value integer [NOT NULL]
  fecha timestamp  
  commentar varchar
}


Ref: "groups"."id" < "user_group"."group_id"

Ref: "track"."group" < "groups"."id"

Ref: "friends"."friend1" < "auth"."users"."username"

Ref: "friends"."friend2" < "auth"."users"."username"

Ref: "auth"."users"."username" < "user_group"."user_id"

Ref: "track"."group" < "log"."track_group"
Ref: "track"."title" < "log"."track_title"

Ref: "log"."user_id" < "auth"."users"."username"
